### PR TITLE
Fixed "unauthenticated git protocol" error

### PR DESCRIPTION
**Pull request by hector-vido**
Github disable the unauthenticated connection through SSH as we can see here:

https://github.blog/2021-09-01-improving-git-protocol-security-github/

I just changed every file to use https instead.

image

### CODE REVIEW

**Comment by tst2005** [comment]
FYI, luarocks 3.8.0 support it without change (see https://github.com/luarocks/luarocks/commit/9ff512e35455939f02eaec2318e3acc77782fdeb )

**Comment by hector-vido** [comment]
Good to know.
But is not a good a idea fix this to avoid problems with people using old versions?

**Comment by tst2005** [comment]
@hector-vido I'm just annoyed by an arbitrary change that breaks everything, especially when the blog asks everyone to fix it themselves. I was dreaming of being able to comment on this blog to provide workarounds, until all existing repositories are fixed (that is a huge work)! thanks github, thanks micros*ft!

Another [workaround (without luarocks upgrade)](https://github.com/ledgetech/lua-resty-http/pull/270#issue-1175653140)

**Comment by hector-vido** [comment]
Sorry man, I just trying to help, I though this was a good idea because is simple, and I can't see why this change will break something.
What blog you're talking about?

**Comment by tst2005** [comment]
@hector-vido sorry I didn't mean to offend you. Don't take my answer against you. I follow lot of lua projets, I see and understand you just want to help. I had to rant against github/microsoft.
( The blog I talk is https://github.blog/2021-09-01-improving-git-protocol-security-github/ )

**Comment by hector-vido** [comment]
Next time, please, tell me "I will not accept this because ..."

**Pull request closed without merging**
